### ISSUE TITLE
git submodules error (and documentation)

### ISSUE THREAD

**Issue by chadrik** [mikrosimage/duke#1]
Hi,
I'm working on compiling Duke and I'm running into some problems with git submodules.
1. it would be great to mention that you need to pull them in the README.md.   I ended up getting an error during compilation like this: "error: Could not find a Jamfile in directory 'src/duke/submodules/dukeplugins'."  and I figured out from the .gitmodules file that those were in a git submodule.
2. the sequenceparcer plugin will not clone due to a bad hash:

```
chad$ git clone --recursive https://github.com/mikrosimage/duke.git
Cloning into duke...
remote: Counting objects: 5079, done.
remote: Compressing objects: 100% (2169/2169), done.
remote: Total 5079 (delta 3105), reused 4857 (delta 2883)
Receiving objects: 100% (5079/5079), 952.08 KiB | 525 KiB/s, done.
Resolving deltas: 100% (3105/3105), done.
Submodule 'src/duke/submodules/concurrent_utils' (git://github.com/mikrosimage/concurrent_utils.git) registered for path 'src/duke/submodules/concurrent_utils'
Submodule 'src/duke/submodules/dukeplugins' (git://github.com/mikrosimage/dukeplugins.git) registered for path 'src/duke/submodules/dukeplugins'
Submodule 'src/duke/submodules/sequenceparser' (git://github.com/mikrosimage/sequenceparser.git) registered for path 'src/duke/submodules/sequenceparser'
Cloning into src/duke/submodules/concurrent_utils...
remote: Counting objects: 205, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 205 (delta 98), reused 198 (delta 91)
Receiving objects: 100% (205/205), 38.52 KiB, done.
Resolving deltas: 100% (98/98), done.
Submodule path 'src/duke/submodules/concurrent_utils': checked out '6d9a933ff58da989c2ef12fd3760eaa9cb41ae46'
Cloning into src/duke/submodules/dukeplugins...
remote: Counting objects: 237, done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 237 (delta 67), reused 228 (delta 58)
Receiving objects: 100% (237/237), 104.36 KiB, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'src/duke/submodules/dukeplugins': checked out '94459a9d3621f73d13660769da05ec15cfaf1573'
Cloning into src/duke/submodules/sequenceparser...
remote: Counting objects: 829, done.
remote: Compressing objects: 100% (366/366), done.
remote: Total 829 (delta 501), reused 748 (delta 423)
Receiving objects: 100% (829/829), 191.48 KiB | 292 KiB/s, done.
Resolving deltas: 100% (501/501), done.
fatal: reference is not a tree: 1af64d1614148b5f5db03fa6e11b86b0e03c9662
Unable to checkout '1af64d1614148b5f5db03fa6e11b86b0e03c9662' in submodule path 'src/duke/submodules/sequenceparser'
```

**Comment by gchatelet** [comment]
Hi Chad,

Sorry for the lag but we just discovered we were receiving no notification from github, thus the late discovery of your issues.

First of all, thanks a lot for reporting. You're absolutely right. it looks like I did break everything pushing a duke version referencing a local sequence_parser branch. My bad.

Just to let you know, due to change in priorities here at Mikros, @nrondaud and I are no more full time on Duke ( more spare time actually ) for the next two months. So you'll notice a decrease in github statistics and maybe a bit of a latency in our responses.

I shall add that we're in the middle of simplifying duke's code by removing several libraries. Basically dropping openal, libsndfile, directX and sfml for Qt+OpenGL. We'd also like to remove Cg from the dependencies. This will help getting more people in the community so maybe you should wait a bit to ease the pain.

Thanks again for the feedback. I'm taking this issue.

**Comment by gchatelet** [comment]
I pushed a new version (1.3.1 merged to master) correcting the bad hash, I also updated the documentation to quote the versions of the libraries we're using. Let me know if it still doesn't build.
