### ISSUE TITLE
errors when loading files

### ISSUE THREAD

**Issue by cellstorm** [mikrosimage/duke#50]
on Ubuntu 12.04, with stable version, Linux 64 / g++ 4.8; downloaded 16. jan

loading a .tif (converted from .dng with imagemagick, http://paste.ubuntu.com/6767325/ ) gives error:

Unexpected error
Don't know how to convert internal image format Unknown to pixel type
djv reads it w/o problems; in duke UNSTABLE it works

loading a .dpx converted with imagemagick, http://paste.ubuntu.com/6767315/
![screenshot from 2014-01-17 12 14 19](https://f.cloud.github.com/assets/937913/1939739/8ef33de6-7f68-11e3-8d9c-e21ad72a363b.png); have the binary Nvidia driver installed.
djv reads it w/o problems; in duke UNSTABLE it has the same issue.

files at openartisthq.org/0002CD.tar.bz2

btw, duke has such a beautiful icon, would be nice to have it in window frame, as well as dukes name (note the unnamed window in the screenshot)

**Comment by gchatelet** [comment]
Thx for the bug report I'm looking into this.
For now I think the FastDPX plugin that comes with Duke expect some _classic_ dpx file format.
OpenImageIO will probably handle this dpx just fine though. I'll get back to you with a solution.

**Comment by gchatelet** [comment]
My previous comment is not very clear so I'm restating here.
We have two plugins to handle dpx, a fast one that directly maps file to memory and one based on openimageio that actually transcode the dpx to 16 bits (aka slower because some processing occurs).

The FastDpx one only accepts 10bit filled RGB dpx ( in this case this is a 16 bit dpx ) but reports no error.

I'll submit a fix on _develop_ so that FastDpx rejects this format and openimageio will take over.
