### ISSUE TITLE
space in filename

### ISSUE THREAD

**Issue by reytrace** [mikrosimage/duke#9]
opensuse 12.1
when loading a file if the file name has spaces duke closes.
ie: duke "my file.jpg"

**Comment by gchatelet** [comment]
I cannot reproduce the issue with duke alone.
Maybe it's because of the duke.sh shell script with the forwarding arguments `$*` ?
Can you try with `"$@"` instead which should be safer according to this [stackoverflow](http://stackoverflow.com/questions/1537673/how-do-i-forward-parameters-to-other-command-in-bash-script)

**Comment by reytrace** [comment]
ok this works with "$@"
